### ISSUE TITLE
How to use local path to deploy model?

### ISSUE THREAD

**Issue by dblate** [ServerlessLLM/ServerlessLLM#128]
### Prerequisites

- [X] I have read the [ServerlessLLM documentation](https://serverlessllm.github.io/).
- [X] I have searched the [Issue Tracker](https://github.com/ServerlessLLM/ServerlessLLM/issues) to ensure this hasn't been reported before.

### System Information

- ServerlessLLM 0.5.0 
- Linux with 2 GPUs

### Problem Description

In quick start guide(https://serverlessllm.github.io/docs/stable/getting_started/quickstart), the deploy command is "sllm-cli deploy --model facebook/opt-1.3b".
I can not connect to HuggingFace for now, but I have the model in my local disk, how can I use the local path to deploy model?

### Steps to Reproduce

Code snippets:
```python

```

Steps to reproduce:
1.
2.
3.

**Comment by dblate** [comment]
It seems that I can not just simply use absolute path in deploy config.json "pretrained_model_name_or_path" field, like
"pretrained_model_name_or_path": "/root/models/xx/"

**Comment by future-xy** [comment]
Thank you for your feedback! We're aiming to implement this missing feature in the next one or two releases.

In the meantime, you can work around this by converting the Transformers model checkpoint to sllm format and saving it to the designated model path (e.g., the default path is ./models/transformers/). This approach works because the model downloader will skip downloading if it detects that the required model already exists in the specified path. For reference, see the relevant code here:
https://github.com/ServerlessLLM/ServerlessLLM/blob/da683eefe109da5c803841137cbf291733189a16/sllm/serve/model_downloader.py#L43-L48

Below is an example script for converting a local Transformers model:

```python
from sllm_store.transformers import save_model

# Load a model from a local path
import torch
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('YOUR_LOCAL_MODEL_PATH/facebook/opt-1.3b', torch_dtype=torch.float16)

save_model(model, './models/transformers/facebook/opt-1.3b')
```

This should help for now! Let us know if you have further questions or run into any issues.

**Comment by dblate** [comment]
Thanks for your detailed answer, I can work around now by your solution.
