### ISSUE TITLE
[BUG] `sllm-cli` reports successful deployment despite failure

### ISSUE THREAD

**Issue by JustinTong0323** [ServerlessLLM/ServerlessLLM#24]
**Describe the bug**
The `sllm-cli` tool reports successful model deployment even though the model is not actually deployed successfully.

**To Reproduce**
0. Code snippets
   ```bash
   ➜   sllm-cli deploy --model "facebook/opt-2.7b"
   INFO 07-19 15:44:06 deploy.py:68] Deploying model facebook/opt-2.7b with default configuration.
   ERROR 07-19 15:47:40 deploy.py:85] Failed to register model. Status code: 500. Response: Internal Server Error
   ➜   sllm-cli deploy --model "facebook/opt-2.7b"
   INFO 07-19 15:49:50 deploy.py:68] Deploying model facebook/opt-2.7b with default configuration.
   INFO 07-19 15:49:50 deploy.py:83] Model registered successfully.
   ```
1. Run `sllm-cli deploy --model "facebook/opt-2.7b"`

**Expected behavior**
The model should be deployed successfully on the first attempt, or if the deployment fails, subsequent attempts should not falsely report success.

**Server Info:**
- OS: Ubuntu 22.04.4 LTS
- GPU: 4 * A6000 (**GPU0 is in use by another user**)

**Additional context**
I attempted to deploy the model according to the quickstart guide. The first attempt failed with an error indicating **CUDA out of memory**. Subsequent attempts returned an OK status, but the model was not actually deployed successfully, as evidenced by failed inference attempts.

**Comment by future-xy** [comment]
A similar bug, `sllm-cli` reports successfully sent but actually the delete operation failed because the model name doesn't exist. I think `sllm-cli` and the controller need to be improved together, i.e., using error code and message.
```bash
$ sllm-cli delete facebook/opt-1.3b facebook/2.7b
INFO 07-31 03:16:10 delete.py:54] Successfully sent the request to delete model facebook/opt-1.3b
INFO 07-31 03:16:10 delete.py:54] Successfully sent the request to delete model facebook/2.7b
```

**Comment by SiyangShao** [comment]
This is usually because for most operations, we do not have a return value for that and if it didn't raise error, the applib will always assume it exected successfully. And another possible way is to use `try...except` in python. But according to their [document](https://docs.ray.io/en/latest/ray-core/fault_tolerance/tasks.html), all exceptions here are wrapped as `RayTaskError`, and we may handle it as following
https://github.com/ServerlessLLM/ServerlessLLM/blob/8796d1386393ce3bf18151b7d4e84fa2cf052359/serverless_llm/serve/app_lib.py#L73-L81
Which kind do you think is better? Add return code for controller logic or use exception handling?
